# https://www.flashmq.org/documentation/config-file/

listen {
    protocol mqtt
    inet_protocol ip4
    inet4_bind_address 0.0.0.0
    port 1883
}

bridge {
   address 172.19.1.52
   port 1884
   tls off
   protocol_version mqtt5
   keepalive 600
   bridge_protocol_bit false
   publish topic 1
   subscribe topic 1
}

#thread_count 1
allow_anonymous true
log_file    /tmp/flashmq/flashmq.log
#log_level   error
storage_dir /tmp/flashmq
