listener 1883
allow_anonymous true

connection bridge1
address 172.19.1.52:1884   
restart_timeout 1
topic topic both 1 local/ remote/
topic topic both 1

keepalive_interval 600
remote_clientid mosquitto

#bridge_protocol_version mqttv311
bridge_protocol_version mqttv50

notifications false
cleansession true