/*
 * LoopFuzz: Protocol-Specific Semantic Oracle Framework
 * =========================================================
 *
 * Extends crash-only triage with semantic/logic vulnerability-candidate
 * generation based on RFC security invariants.  These reports are not
 * confirmed vulnerabilities until replay, configuration review, root-cause
 * analysis, and security-impact validation are completed.
 *
 * Detection methodology (recalibrated 2026-07-06):
 *   1. MEDIUM+ reports require evidence that the server accepted the
 *      specific malformed/out-of-state request, not just any response in
 *      the same cumulative buffer.
 *   2. Rules that only observe client-generated bytes, configuration
 *      choices, or standard-permitted behaviour are INFO/LOW or removed.
 *   3. Protocol-specific correlation is preferred over positional matching:
 *      RTSP uses CSeq, MQTT uses packet identifiers, HTTP counts real
 *      header lines, and text protocols require precise success codes.
 *      Ambiguous correlations (for example repeated RTSP CSeq values) are
 *      suppressed instead of guessed.
 *   4. FTP/SMTP command state is line-tokenized on CR or LF and response-bound
 *      at response-consuming line granularity because AFLNet request regions
 *      can contain multiple malformed command fragments and servers also answer
 *      unknown lines.
 *   5. Counters and replayable-violations reports represent reportable
 *      MEDIUM+ candidates only.  INFO/LOW entries remain non-reportable
 *      observations and must not be presented as vulnerability candidates.
 *   6. Saved candidate reports are triage artifacts: the text report is a
 *      bounded human-readable summary, while complete request/response bytes
 *      are stored as binary sidecar files for manual replay and validation.
 *
 * Calibration summary:
 *   FTP:  command-state checks bind USER/PASS/RNFR/RNTO/data commands through
 *         response-consuming line slots; auth bypass requires absence of prior
 *         230 login evidence; RNTO candidates are suppressed on explicit 503
 *         sequence rejection or prior 350 RNFR evidence; CRLF heuristic removed;
 *         traversal syntax without leaked content is LOW only.
 *   SMTP: relay requires external recipient + RCPT accept + DATA accept +
 *         final queue evidence, all bound through response-consuming line
 *         slots; RCPT/DATA state candidates are suppressed when the cumulative
 *         response contains explicit syntax/state rejection evidence; STARTTLS
 *         downgrade is suppressed on explicit security rejection; VRFY/EXPN is
 *         LOW config observation.
 *   RTSP: PLAY/RECORD-before-SETUP candidates require a syntactically valid
 *         RTSP request line without a Session header, method-local unique CSeq
 *         correlation, method-shaped success response (PLAY needs Session plus
 *         RTP-Info/Range; SDP bodies are not PLAY/RECORD success), and no prior
 *         successful SETUP evidence from either request-side matching or
 *         response-side blocks; repeated CSeq values suppress MEDIUM+ reports;
 *         transport-parser anomalies are LOW without crash/hang evidence.
 *   SIP:  no active findings for the benchmark config; auth is not enabled
 *         and reliable SIP triage needs CSeq/branch-aware matching.
 *   DAAP: /databases without session requires a DAAP database body in the
 *         matching response block; path traversal requires leaked sensitive
 *         content in that block; /server-info field names are LOW context.
 *   HTTP: path traversal requires sensitive content leakage in the matching
 *         response block; CL/TE and conflicting Content-Length are MEDIUM
 *         candidates requiring proxy/differential validation; response-splitting
 *         byte markers and chunk parser-stress without split/crash/resource
 *         proof are LOW; Server header fingerprinting and auth-bypass byte
 *         heuristics are removed.
 *   MQTT: CONNECT parsing is bounds-checked; v5 properties are parsed from
 *         the real properties section and require successful CONNACK before
 *         becoming reportable; zero-length SUBSCRIBE topic filters require a
 *         valid SUBSCRIBE fixed header, nonzero packet id, zero topic length,
 *         QoS byte, and matching successful SUBACK; they are protocol/state
 *         candidates, not DoS, unless crash/hang evidence is produced by the
 *         AFL/AFLNet crash pipeline; large v5 user-property lists are LOW
 *         context without resource telemetry; empty ClientID is INFO only when
 *         clean_session is false.
 */

#ifndef __PROTOCOL_ORACLE_H
#define __PROTOCOL_ORACLE_H

#include <stdint.h>
#include <stddef.h>

/* ============================================
 * Oracle Violation Severity Levels
 * ============================================ */

#define ORACLE_SEV_NONE     0   /* No violation */
#define ORACLE_SEV_INFO     1   /* Informational (potential info leak) */
#define ORACLE_SEV_LOW      2   /* Low severity (unusual behavior) */
#define ORACLE_SEV_MEDIUM   3   /* Medium (state machine violation) */
#define ORACLE_SEV_HIGH     4   /* High (auth bypass, path traversal) */
#define ORACLE_SEV_CRITICAL 5   /* Critical (RCE indicator, full bypass) */

/* ============================================
 * Oracle Violation Categories
 * Maps to security properties from FindVulnerability.txt
 * ============================================ */

#define ORACLE_CAT_NONE             0x0000
#define ORACLE_CAT_AUTH_BYPASS      0x0001  /* Authentication */
#define ORACLE_CAT_AUTHZ_BYPASS     0x0002  /* Authorization */
#define ORACLE_CAT_STATE_VIOLATION  0x0004  /* State Consistency */
#define ORACLE_CAT_INFO_LEAK        0x0008  /* Confidentiality */
#define ORACLE_CAT_PATH_TRAVERSAL   0x0010  /* Integrity */
#define ORACLE_CAT_INJECTION        0x0020  /* Integrity */
#define ORACLE_CAT_DOS              0x0040  /* Availability */
#define ORACLE_CAT_RESOURCE_EXHAUST 0x0080  /* Availability */
#define ORACLE_CAT_ISOLATION        0x0100  /* Isolation */
#define ORACLE_CAT_REPLAY           0x0200  /* State Consistency - double spend */
#define ORACLE_CAT_SMUGGLING        0x0400  /* Integrity - request smuggling */

/* ============================================
 * Evidence Quality Levels
 *
 * Indicates HOW the oracle verified that the server actually
 * exhibited the flagged behavior.  Higher quality = stronger
 * evidence, lower risk of false positives.
 * ============================================ */

#define ORACLE_EVIDENCE_STRONG      3  /* Response code precisely matched (==230,==150, SUBACK pktID) */
#define ORACLE_EVIDENCE_MODERATE     2  /* Response code range matched (>=200, 150-250) + position verified */
#define ORACLE_EVIDENCE_WEAK        1  /* Response content pattern only — no per-request response mapping */
#define ORACLE_EVIDENCE_HEURISTIC   0  /* Heuristic/aggregate threshold — weakest signal */

/* Maximum violations per check */
#define ORACLE_MAX_VIOLATIONS 16

/* ============================================
 * Violation Report Structure
 * ============================================ */

typedef struct {
    uint8_t  severity;           /* ORACLE_SEV_* */
    uint16_t category;           /* ORACLE_CAT_* bitmask */
    uint8_t  evidence_quality;   /* ORACLE_EVIDENCE_* — how strong the server-behavior evidence is */
    uint32_t pattern_hash;       /* For deduplication */
    char     description[256];   /* Human-readable description of observed deviation */
    char     cve_reference[64];  /* Related CVE pattern if known and target-matched */
    int      request_index;      /* Which request triggered this */
} oracle_violation_t;

typedef struct {
    oracle_violation_t violations[ORACLE_MAX_VIOLATIONS];
    int violation_count;
    uint8_t max_severity;        /* Highest severity found */
    uint16_t categories_hit;     /* OR of all categories */
} oracle_result_t;

/* ============================================
 * Protocol State Tracking
 * ============================================ */

typedef struct {
    uint8_t authenticated;       /* Has client authenticated? */
    uint8_t connected;           /* Is connection established? */
    uint8_t tls_active;          /* Is TLS/encryption active? */
    uint8_t admin_mode;          /* Is client in admin/privileged mode? */
    int     auth_attempts;       /* Number of auth attempts */
    int     commands_sent;       /* Total commands sent before auth */
    int     commands_after_auth; /* Total commands sent after auth */
    int     current_state;       /* Protocol-specific state enum */
    char    last_command[64];    /* Last command sent */
    int     last_response_code;  /* Last response code received */
} protocol_state_t;

/* FTP state machine states */
#define FTP_STATE_INIT       0
#define FTP_STATE_USER_SENT  1
#define FTP_STATE_LOGGED_IN  2
#define FTP_STATE_PASSIVE    3
#define FTP_STATE_TRANSFER   4

/* SMTP state machine states */
#define SMTP_STATE_INIT      0
#define SMTP_STATE_EHLO      1
#define SMTP_STATE_AUTH      2
#define SMTP_STATE_MAIL      3
#define SMTP_STATE_RCPT      4
#define SMTP_STATE_DATA      5

/* RTSP state machine states */
#define RTSP_STATE_INIT      0
#define RTSP_STATE_DESCRIBED 1
#define RTSP_STATE_SETUP     2
#define RTSP_STATE_PLAYING   3

/* SIP state machine states */
#define SIP_STATE_INIT       0
#define SIP_STATE_REGISTER   1
#define SIP_STATE_INVITED    2
#define SIP_STATE_CONFIRMED  3

/* MQTT state machine states */
#define MQTT_STATE_INIT      0
#define MQTT_STATE_CONNECTED 1
#define MQTT_STATE_SUBSCRIBED 2
#define MQTT_STATE_PUBLISHING 3

/* HTTP state machine states */
#define HTTP_STATE_INIT      0
#define HTTP_STATE_AUTHED    1

/* ============================================
 * Main Oracle API
 * ============================================ */

/*
 * Initialize oracle for a specific protocol.
 * Call once at fuzzer startup.
 */
void oracle_init(const char *protocol_name);

/*
 * Check a request-response pair for security violations.
 *
 * @param protocol_name  Protocol identifier (e.g., "FTP", "MQTT")
 * @param requests       Array of request buffers sent
 * @param req_lens       Array of request lengths
 * @param req_count      Number of requests
 * @param response       Server response buffer
 * @param resp_len       Response length
 * @param result         Output: violation results
 *
 * @return Number of violations found
 */
int oracle_check(
    const char *protocol_name,
    const unsigned char **requests,
    const unsigned int *req_lens,
    int req_count,
    const unsigned char *response,
    unsigned int resp_len,
    oracle_result_t *result
);

/*
 * Check if a violation pattern is new (not seen before).
 * Uses a dedup bitmap internally.
 */
int oracle_is_new_violation(uint32_t pattern_hash);

/*
 * Save a violation report to the output directory.
 *
 * `requests` / `req_lens` / `req_count` describe the per-message
 * boundaries of the triggering sequence (built from the kl_messages
 * linked list at the call site).  They are saved to a sidecar
 * `.request.replay` file in the AFLNet length-prefixed format
 * ([u32 LE size][payload]...), so that `aflnet-replay` can reproduce
 * the exact message sequence in standalone mode — unlike the raw
 * `request_data` blob, which drops message boundaries and therefore
 * cannot be replayed faithfully.
 */
void oracle_save_violation(
    const char *out_dir,
    const oracle_result_t *result,
    const unsigned char *request_data,
    unsigned int request_len,
    const unsigned char *response_data,
    unsigned int response_len,
    const unsigned char **requests,
    const unsigned int *req_lens,
    int req_count
);

/*
 * Get oracle statistics string for status display.
 */
const char* oracle_stats_string(void);

/* ============================================
 * Protocol-Specific Oracle Functions
 * ============================================ */

int oracle_check_ftp(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_smtp(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_rtsp(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_sip(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_daap(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_http(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

int oracle_check_mqtt(
    const unsigned char **requests, const unsigned int *req_lens,
    int req_count, const unsigned char *response, unsigned int resp_len,
    oracle_result_t *result);

/* ============================================
 * Telemetry counters (extern, defined in protocol-oracle.c)
 * ============================================ */

extern uint64_t oracle_total_checks;
extern uint64_t oracle_total_violations;
extern uint64_t oracle_unique_violations;
extern uint64_t oracle_auth_bypass_count;
extern uint64_t oracle_state_violation_count;
extern uint64_t oracle_info_leak_count;
extern uint64_t oracle_path_traversal_count;
extern uint64_t oracle_dos_count;

#endif /* __PROTOCOL_ORACLE_H */
